# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c076a385030e5ad66568694383bf4c02678c20241c8856dcb00b663b0e3b07db091281f39298138e7c8bb319e788c37ff590980258ae5258be483474eecf4ff6

test:
  secret_key_base: 90329a34b49aee8831b821203c7172ba516c411be1bc13dad21f2dde3376b75de142c98e15d78ae84b0ce34056d531f2a978917282654b2dcc77ee17fb29d3c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
